### ISSUE TITLE
Exclude Dimension from AlternateLanguageLinks

### ISSUE THREAD

**Issue by samuelhauser** [neos/neos-seo#101]
Add a possibility not only to include, but also to exclude dimensions.

**Comment by Sebobo** [comment]
This will only be possible (in a good way) with the Fusion based DimensionMenu in Neos 4.3. 
We'll have to see if it will be possible for 3.0 release.

**Comment by Sebobo** [comment]
@samuelhauser can you check out #112, that should solve your problem.

**Comment by samuelhauser** [comment]
@Sebobo I really like it. thx for your changes
