### ISSUE TITLE
Translation Tag Missing

### ISSUE THREAD

**Issue by drlimbo** [neos/neos-seo#120]
This is a:
* [x] bug

* Version: 3.0.0
* Platform/Target and Browser Versions: Chrome 73 on OSX

### What you did
Upgraded to Neos 4.3 and Neos.SEO 3

### Expected Behavior
See a placeholder text

### Actual Behavior
Placeholder displays:
`Neos.Seo:NodeTypes.TitleTagMixin:properties.titleOverride.textAreaEditor.placeholder`

I think there's a language Tag Missing. 

@jonnitto 
> @Sebobo Mach bitte ein issue auf Neos SEO, und mention Jon

**Comment by Sebobo** [comment]
I think this might be that https://github.com/neos/neos-development-collection/pull/2404 is missing in 4.3 due to a merge error.
