### ISSUE TITLE
queryParameters should not be URL-Encoded in Neos.Seo:StructuredData.Website.SearchAction

### ISSUE THREAD

**Issue by drlimbo** [neos/neos-seo#123]
This is a (multiple allowed):
* [x] bug

* Neos.Seo Version: 3.0.2
* Neos Version: 4.3.0

### What you did
Added targetNode to Neos.Seo:StructuredData.Website
```
prototype(Neos.Seo:StructuredData.Website) {
    potentialAction.targetNode = ${q(site).find('[instanceof Vendor.ElasticSearch:Document.Searchresults]').get(0)}
}
```

### Problem
queryParameter search "{search_term_string}" should not be encoded to "%7Bsearch_term_string%7D". [Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool/u/0/) returns an Error. 

### Expected Behavior
```
<script type="application/ld+json">{  
   ...
   "potentialAction":{  
	  ...
      "target":"http:\/\/domain.tld\/suche?search={search_term_string}"
   }
}</script>
```

### Actual Behavior
```
<script type="application/ld+json">{  
   ...
   "potentialAction":{  
	  ...
      "target":"http:\/\/domain.tld\/suche?search=%7Bsearch_term_string%7D"
   }
}</script>
```

**Comment by Sebobo** [comment]
@drlimbo can you check out #125 and verify that it works for you?

**Comment by drlimbo** [comment]
Thanks @Sebobo [#125](https://github.com/neos/neos-seo/pull/125) fixes the problem for me!
