### ISSUE TITLE
ImageHelper.php should pass the quality parameter when building thumbnails

### ISSUE THREAD

**Issue by klfman** [neos/neos-seo#137]
This is a (multiple allowed):
* [] bug
* [x] enhancement
* [] feature-discussion (RFC)

The fusion helper `ImageHelper.php` should also set the "quality" parameter in the `ThumbnailConfiguration`, as this allows the user to expicitly lower the quality of the obtained thumbnail.

**Comment by Sebobo** [comment]
You can check out the PR #138. Is is the same you did in your version?

**Comment by klfman** [comment]
Yep, that's the same!
