### ISSUE TITLE
Sitemap does not update after modification

### ISSUE THREAD

**Issue by mficzel** [neos/neos-seo#141]
After updating documents the sitemap does not update properly. The reason is that the prototype "Neos.Seo:XmlSitemap" does define cache tags for the body but no cache mode and cache identifier.

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Version: current

**Comment by Sebobo** [comment]
Curious, I'm sure I added a whole configuration at some point and even debugged it a few times...

**Comment by mficzel** [comment]
Maybe you altered the site document during testing. This one is covered in the cache annotation on the Default.fusion in Neos.Neos
