### ISSUE TITLE
TwitterCard ignores type prop when evaluating the thumbnail preset

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-seo#148]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Version: 3.1.1 (probably all above 3.0)
* Platform/Target and Browser Versions: irrelevant

### What you did

Changed the default type of the TwitterCard via
```
prototype(Neos.Seo:TwitterCard) < prototype(Neos.Fusion:Component) {
    type = ${q(node).property('twitterCardType') || 'summary_large_image'}
}
```

### Expected Behavior

The `Neos.Seo:TwitterCard.SummaryCardLargeImage` thumbnail preset is used to render the image URL by default

### Actual Behavior

The `Neos.Seo:TwitterCard.SummaryCard` is used unless the `twitterCardType` is set to "summary_large_image"

### Background

The problem seems to be the following condition in the preset case:
```
condition = ${q(node).property('twitterCardType') == 'summary_large_image'}
```

that should depend on the `type` prop not on the node property

### Work around

```
prototype(Neos.Seo:TwitterCard) < prototype(Neos.Fusion:Component) {
    type = ${q(node).property('twitterCardType') || 'summary_large_image'}
    image.preset.summaryCardLargeImage.condition = ${q(node).property('twitterCardType') || q(node).property('twitterCardType') == 'summary_large_image'}
}
```

**Comment by jonnitto** [comment]
I think we have to use `@context` for a proper fix or nested `Neos.Fusion:Component`. I would prefer the nested variant, but this would be breaky.
