### ISSUE TITLE
Pages that refer to another page in their canonical tag should not appear in the sitemap 

### ISSUE THREAD

**Issue by daniellienert** [neos/neos-seo#159]
* Version: all

### Expected Behavior
Pages that have a page referenced as canonical are not visible in the index.
https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap: 

_List only canonical URLs in your sitemaps. If you have two versions of a page, list in the sitemap only the one you prefer to appear in search results. If you have two versions of your site (for example, www and non-www), decide which is your preferred site, and put the sitemap there, and add rel=canonical or redirects on the other site._

**Comment by Sebobo** [comment]
So as soon as there any canonical set or only when set to a node?
