### ISSUE TITLE
Neos.Seo: TASK: Improve ESCR Compatibility

### ISSUE THREAD

**Issue by ahaeslich** [neos/neos-seo#171]
Current v4 branch was introduced for Neos 9.0.

ToDo's:

- [x] Check for `node.context` usages https://github.com/neos/neos-seo/pull/172
- [x] Check usage of site object
- [x] Refactor `robots.txt` to properly use ESCR
- [x] Refactor `XmlSitemapUrlsImplementation` to use the ESCR api https://github.com/neos/neos-seo/pull/173
- [x] Check cache settings
- [x] Update documentation

Related issues / pull request in neos/neos-development-collection to support all features again:
- neos/neos-development-collection#4074
- neos/neos-development-collection#4085
- neos/neos-development-collection#4107
- neos/neos-development-collection#4249

**Comment by so-grimm** [comment]
Already known issue with Neos 9.0:
The `lang` attribute doesn't work anymore.

Solution:
`Neos.Seo/Resources/Private/Fusion/Metadata/LangAttribute.fusion` -> the `@if` conditions need to be fixed
