### ISSUE TITLE
Remove Twitter integration

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-seo#176]
Twitter does not exist anymore and Mastodon and probably other (newer) networks uses OpenGraph.

**Comment by Sebobo** [comment]
Feedback and opinions are welcome how we should proceed here.
Other CMS are already removing their integrations afaik.

**Comment by jonnitto** [comment]
We could also just remove the mixins from Neos.Neos:Page. That way, it would be easy to activate it if someone want's to use it.

**Comment by paavo** [comment]
We always disabled the "Twitter-Integration" and sticked to OpenGraph only. 
I would vote for removing for a cleaner code base.

**Comment by kdambekalns** [comment]
Does "X" read OpenGraph? If so, by all means, get rid of it. It not, we might want to leave it in but disable it by default, as @jonnitto suggested.

Possibly tweak the labels to read "X (formerly known as Twitter)". 🤣

**Comment by Sebobo** [comment]
According to their docs they use OpenGraph if available https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started#opengraph except for `twitter:site` `twitter:card` and `twitter:creator`, which are "X"-exclusive.
So at least we could remove some of the other attributes in any case.

Another option would be to create a separate package that implements "X" and extends Neos.Seo.

But right now I wouldn't even know what to call things, as the naming could be different next week already again 🤪

**Comment by kdambekalns** [comment]
> But right now I wouldn't even know what to call things, as the naming could be different next week already again

Well, "X" can stay, it looks like a placeholder anyway. 🤷

**Comment by Sebobo** [comment]
So I created a PR to remove everything for Neos 9. 

I would leave the rest to the community and for now don't change much for the 3.x branch as long as nothing breaks from their side.
