### ISSUE TITLE
Command for cleaning up storage / target

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-seo#18]
Jira issue originally created by user @robertlemke:

After deploying a new version of an application (or in other situations where you lost track of which files are needed), an administrator or automated deployment needs to be able to sweep unused resources from a local / remote storage or target.

 Jira-URL: https://jira.neos.io/browse/NEOS-680

**Comment by kdambekalns** [comment]
This is not related to the SEO package at all… Seems the bot got confused. :)

@robertlemke If this is still of relevance, please open a fresh issue. Thanks!
