### ISSUE TITLE
BUG: Errors when upgrading from 8.3 to Neos 9

### ISSUE THREAD

**Issue by pKallert** [neos/neos-seo#182]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Version: 4.1.3
* Platform/Target and Browser Versions: macOS, Chrome

### What you did
I tried to upgrade from Neos 8.3 to Neos 9.0. To do that, I upgraded neos-seo from 3.3.4 to 4.1.3 since this is the latest version and ran the migration using `cr:migrateLegacyData`. 

### Expected Behavior
I expect to be able to use the latest version of neos-seo when migrating to Neos 9 or at least have some documentation that mentions that I should only user neos-seo 4.1.0 when migrating the database to Neos 9 .

### Actual Behavior
With the new changes in Neos, I get the following error while upgrading:

![Bildschirmfoto 2023-12-14 um 10 21 49](https://github.com/neos/neos-seo/assets/91674611/f3548134-e968-47f0-99da-cca1b688a459)
This is because the twitter cards were removed in 4.1.2: https://github.com/neos/neos-seo/commit/41bade5db99335c24ddd41cde0064cb6b09f42ba 

### Possible solutions 

- Remove twitter card also for neos-seo for Neos 8 with a migration
- Document how to migrate data to Neos 9 in this package

**Comment by markusguenther** [comment]
So I created a PR to remove everything for Neos 9. 

I would leave the rest to the community and for now don't change much for the 3.x branch as long as nothing breaks from their side.

_Originally posted by @Sebobo in https://github.com/neos/neos-seo/issues/176#issuecomment-1676794889_

**Comment by Sebobo** [comment]
Sounds more like a general upgrade issue with Neos 9.0 which could happen with other packages too?
Or do you think it's something specific here.

**Comment by ahaeslich** [comment]
Couldn't it also happen if a project has some node(s) in the database with properties no longer defined by the project itself?

Then it would be a bug in the migration rather than a specific neos/seo issue 🤔

**Comment by markusguenther** [comment]
As the others already mentioned that this is more an issue of the migration, I dive a bit deeper and the legacy migration has two sections where we migrate nodedata properties to events.

Here we need to check if the property is still part of the node type schema and skip the node property migration.
`NodeDataToEventsProcessor::extractPropertyValuesAndReferences` and `NodeDataToAssetsProcessor` resulting in an exception when we migrate node properties that are not existing anymore.

```
try {
    $propertyType = $nodeType->getPropertyType($propertyName);
} catch (\InvalidArgumentException $exception) {
    continue;
}
```

With a little catch, we could prevent that. But that's part of the migration!
