### ISSUE TITLE
Google News sitemap generation

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-seo#19]
Jira issue originally created by user @mgoldbeck:

As site owner I want Neos to publish a News Sitemap for the news items on my page that have been published in the last two days.

 Jira-URL: https://jira.neos.io/browse/NEOS-717

**Comment by kdambekalns** [comment]
see https://support.google.com/webmasters/answer/74288

**Comment by Sebobo** [comment]
This should rather be part of a news extension and extend or use the sitemap of this package. 
This should get easier with some new PRs which allow this.
