### ISSUE TITLE
Validation/Preview of SERP, twitter cards, …

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-seo#20]
Jira issue originally created by user @mgoldbeck:

As editor, I want to be able to check the generated output. For this I need easy access to the validation tools (rich snippet testing, twitter card preview, see "Tools for testing and approval" on http://moz.com/blog/meta-data-templates-123) for the SEO hints used.

 Jira-URL: https://jira.neos.io/browse/NEOS-722

**Comment by Sebobo** [comment]
I propose to either find a super simple script that tries to render those previews in a new preview module or create a basic implementation which just shows what the output is if an editor wants to know what's happening but doesn't know the behavior how the fields are rendered if not set.

**Comment by Sebobo** [comment]
Will close this. This is somewhat solved in the Yoast package and will be worked on there further.
Maybe part of it might go into this package again.
