### ISSUE TITLE
Support author/publisher linking

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-seo#21]
Jira issue originally created by user @mgoldbeck:

OpenGraph/Dublin Core elements to specify author and publisher should be embedded in Neos output.

Questions:
- Just links to pages? Author nodetype?
- For facebook really a must to use FB pages urls?
- Restrictions for Google Plus?
- twitter handled by twitter card "creator" element!?
  
  Jira-URL: https://jira.neos.io/browse/NEOS-723

**Comment by Sebobo** [comment]
I'm closing this old one. If there is a more specific requirement we can reopen or create a new issue.
