### ISSUE TITLE
Writing tools / On-page analysis

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-seo#22]
Jira issue originally created by user @mgoldbeck:

Writing tools / On-page analysis

As editor I want helpful hints while creating content:
- proper use of headlines (only one h1, two to three h2/h3 elements)
- use of structural markup to help readers (lists, emphasis, …)
- keyword usage (inverse document frequency and friends)

On a bigger scale some metrics on the site structure would be nice.

 Jira-URL: https://jira.neos.io/browse/NEOS-724

**Comment by Sebobo** [comment]
@mgoldbeck do you still think this makes sense for this package or is better resolved by the yoastseo or other additional analysis package?
