### ISSUE TITLE
Check final title length

### ISSUE THREAD

**Issue by neos-bot** [neos/neos-seo#23]
Jira issue originally created by user @kdambekalns:

The inspector should show a notice if the rendered page title (including anything added by TS and templating) exceeds the recommended maximum (about 50 to 60 characters, configurable).

 Jira-URL: https://jira.neos.io/browse/NEOS-777

**Comment by Sebobo** [comment]
This is covered by the Yoast package and as the page needs to be rendered to calculate the length, the logic needed seems to be too much for this package in my opinion.
