### ISSUE TITLE
BUG: Don't create sitemap entries for references

### ISSUE THREAD

**Issue by rolandschuetz** [neos/neos-seo#24]
When a reference page is created, the sitemap entry contains a url for it's reference. Therefore the references page is inside the sitemap twice.

**Comment by kdambekalns** [comment]
@rolandschuetz With "reference" you mean "shortcut"?

**Comment by rolandschuetz** [comment]
@kdambekalns Sorry for beeing inprecise.

 - Create a new Neos.Neos.Document and call it "test"
 - Now create a new Neos.neos:Shortcut called "test-shortcut" and point it to the Document node "test"

The sitemap.xml will include TWO entries with the same url.

**Comment by aertmann** [comment]
So yes a shortcut. Recently fixed with #35

**Comment by kdambekalns** [comment]
Exactly. Thanks, @aertmann!
