### ISSUE TITLE
Generates malformed hreflang links when parent node is hidden

### ISSUE THREAD

**Issue by peterbucher** [neos/neos-seo#38]
Neos.Seo seems to not check whether Nodes have parents which are set to “hidden”.

It does e.g. make from this hierarchie:
Home
 - LinkNode1
   - LinkNode2 (hidden)
     - PageNode (which should be ignored)

This constellation generates this malformed hreflang Link which causes a 404:
http://domain.com/PageNode

The correct hreflang Link - when no parent is hidden would be:
http://domain.com/LinkNode/LinkNode2/PageNode

And the behaviour i expect when the parent is hidden: Ignore, do not generate hreflang Link at all.

**Comment by peterbucher** [comment]
Correction:
The error lies within the DimensionMenu of Neos.Neos (https://github.com/neos/neos-development-collection/blob/master/Neos.Neos/Classes/Fusion/DimensionsMenuImplementation.php).
To have the Urls correct, the context should include hidden content. And then, if anyone wants not to include childrens of a hidden parent for the alternate language tags, you can do it like:

```
    /**
     * Return TRUE/FALSE if the node's parent (or parent until to the top) is hidden.
     *
     * @param NodeInterface $node
     * @return boolean
     */
    protected function isNodeParentHidden(NodeInterface $node)
    {
        $flowQuery = new FlowQuery([$node]);
        $nodeParents = $flowQuery->parents()->get();

        foreach($nodeParents as $parent) {
            if($this->isNodeHidden($parent)) {
                return true;
            }
        }

        return false;
    }
```
And in "buildItems" (https://github.com/neos/neos-development-collection/blob/master/Neos.Neos/Classes/Fusion/DimensionsMenuImplementation.php#L65) like this:
```
            if ($nodeInDimensions !== null && ($this->isNodeHiddenOrInaccessible($nodeInDimensions) || $this->isNodeParentHidden($nodeInDimensions))) {
                $nodeInDimensions = null;
            }
```

**Comment by Sebobo** [comment]
@peterbucher thx, I'm working on fixing this for the core, but I think your example is incomplete. Did it work for you?

The check for the parents returns empty if they are hidden.

**Comment by peterbucher** [comment]
Hi @Sebobo 

I have currently:
````
    /**
     * Return TRUE/FALSE if the node's parent (or parent until to the top) is hidden.
     *
     * @param NodeInterface $node
     * @return boolean
     */
    protected function isNodeParentHiddenOrInaccessible(NodeInterface $node)
    {
        $flowQuery = new FlowQuery([$node]);
        $nodeParents = $flowQuery->parents()->get();

        foreach($nodeParents as $parent) {
            if($this->isNodeHiddenOrInaccessible($parent)) {
                return true;
            }
        }

        return false;
    }
````

and within the menu Implementation:

```
            if ($nodeInDimensions !== null && ($this->isNodeHiddenOrInaccessible($nodeInDimensions) || $this->isNodeParentHiddenOrInaccessible($nodeInDimensions))) {
                $nodeInDimensions = null;
            }
```

This **does work** for me. What do you mean with "returns empty"?

**Comment by peterbucher** [comment]
Hey @Sebobo 

I missed to post explicitly what did mention: Include hidden content in the context.
This is my updated function in the DimensionMenuImplementation:

```
    /**
     * Get the current node in the given dimensions.
     * If it doesn't exist the method returns null.
     *
     * @param array $dimensions
     * @param array $targetDimensions
     * @return NodeInterface|null
     */
    protected function getNodeInDimensions(array $dimensions, array $targetDimensions)
    {
        $q = new FlowQuery([$this->currentNode]);

        return $q->context(
            [
                'invisibleContentShown' => TRUE,
                'dimensions' => $dimensions,
                'targetDimensions' => $targetDimensions
            ]
        )->get(0);
    }
```

I think this is it.

**Comment by Sebobo** [comment]
@peterbucher OK, nervermind, found a simpler solution: https://github.com/neos/neos-development-collection/pull/2218

**Comment by Sebobo** [comment]
Core patch was merged and will be part of the next releases for Neos >= 3.3.

**Comment by Sebobo** [comment]
@peterbucher good news. The fix was in the patch releases from yesterday up from Neos 3.3 👍
