### ISSUE TITLE
Hide shortcuts with external url in sitemap.xml

### ISSUE THREAD

**Issue by freesh** [neos/neos-seo#39]
Hi,
it looks like the sitemap.xml is listing shortcuts with external urls. This might be a problem for Google bots.

**Comment by kdambekalns** [comment]
Fixed with https://github.com/neos/neos-seo/pull/35 - do we miss a release here? What version of the SEO package do you have?

**Comment by kdambekalns** [comment]
Haha, indeed. Just tagged https://github.com/neos/neos-seo/releases/tag/1.0.13 - please check that as soon as Packagist picked it up.

**Comment by kdambekalns** [comment]
And for Neos 3.x there now is https://github.com/neos/neos-seo/releases/tag/2.0.3

**Comment by kdambekalns** [comment]
That should fix it for real.

**Comment by kitsunet** [comment]
Besides the fact that newer versions need this changed to Neos.Neos:Shortcut. Or did I miss that?

**Comment by kdambekalns** [comment]
That was adjusted in the upmerge… see https://github.com/neos/neos-seo/commit/c72afef37edfe99c70d777c04cae21851d0cb387
