### ISSUE TITLE
More flexible hreflang handling (HTTP headers / XML sitemap)

### ISSUE THREAD

**Issue by kdambekalns** [neos/neos-seo#42]
Currently only `meta` tags are supported, but in some cases using HTTP headers or XML sitemaps might be desired.

Providing hreflang in XML sitemaps is described in https://support.google.com/webmasters/answer/2620865, but noted in https://www.rebelytics.com/hreflang-annotations/ it doesn't need to be high priority:

> Google does not crawl and process XML sitemaps as often as HTML pages and therefore has problems processing the information that is included in sitemaps on time. If you choose this option, you will probably experience lots of hreflang errors in Google Search Console and lots of pages being displayed to the wrong users in Google’s search results.

Having support for HTTP headers is more important, as the same document explains:

> HTTP headers can be set for every URL, including those that do not have their own source code (like the home page that redirects users based on their location or browser languages)

**Comment by Sebobo** [comment]
Hreflang is now supported in Sitemaps since 2.1, therefore I'll close this.
If you think we need the header support, please create an issue. I'm not convinced that we do currently from my research.
