### ISSUE TITLE
Google's new snippet length

### ISSUE THREAD

**Issue by Nikdro** [neos/neos-seo#46]
Google officially confirmed a changed length of snippets on SERPs:

> Over the past week or so, many have been noticing that the snippets were longer than what’s typically been shown.
RankRanger has been tracking these as well, and according to its tools, the snippet length has grown from 160 characters to almost 230 characters on average. 

Taken from: https://searchengineland.com/google-officially-increases-length-snippets-search-results-287596

Shouldn't we change the max length for metaDescription from 156 to 230 ?

**Comment by dlubitz** [comment]
But the article also say:

> Some webmasters and SEOs may consider updating their meta descriptions, but I don’t believe Google would recommend doing so. The snippets are more often dynamically generated based on the user query and content found in both the meta description and the content visible on the page. If Google is going to go with a longer snippet, it likely will pull that content from the page.

Sounds also very reasonable.

**Comment by iseries** [comment]
@dlubitz I think so too. Google recommends nothing. I still don't get why meta description counting is so important. SEO experts say this and that but google never recommended a length for meta description. Interesting tweet by John Mueller: -> https://twitter.com/JohnMu/status/935462155364814848

**Comment by Sebobo** [comment]
I'll close this for now. I think the information from Google is too thin.
Also an interesting article related to that: https://yoast.com/shorter-meta-descriptions/

Most say one should keep the description short.

And it's anyway configurable.
