### ISSUE TITLE
hreflang value is missing

### ISSUE THREAD

**Issue by Lemmork** [neos/neos-seo#56]
Since Version 2.0.7 the value in the hreflang tag is missing.
Eg: Output with Version 2.0.6
<link rel="alternate" hreflang="de" href="https://www.domain.de/">

Output since Version 2.0.7
<link rel="alternate" hreflang href="https://www.domain.de/">

Do I have to make any changes in the configuration, or is this a bug?

On my page I have only one language.

**Comment by Sebobo** [comment]
The hreflang was never rendered when not having a dimension. See `LangAttribute.fusion`.
But you can override the condition in there.

**Comment by Lemmork** [comment]
But I have a contentDimension:

Neos:
  ContentRepository:
    contentDimensions:
      language:
        label: 'Language'
        icon: icon-language
        default: de
        defaultPreset: de
        presets:
          all: null
          de:
            label: Deutsch
            values:
              - de
            uriSegment: ''

My examples are not submitted. Here again:
Output with Version 2.0.6
`<link rel="alternate" hreflang="de" href="https://www.domain.de/">`
Output since Version 2.0.7
`<link rel="alternate" hreflang href="https://www.domain.de/">`

**Comment by Sebobo** [comment]
Maybe same problem as in #54.
Can you check if the same procedure works for your alternate language links?

**Comment by Sebobo** [comment]
@Lemmork I created a PR, maybe you can try if that fixes it for you and comment in the PR.
