### ISSUE TITLE
OpenGraph image tags should enforce absolute urls

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-seo#92]
This currently causes an issue on neoscon.io. The requirement for an absolute url is defined in the protocol http://opengraphprotocol.org
But it seems to not affect all Neos installations.

**Comment by Sebobo** [comment]
@jonnitto do you know if we can somehow enforce absolute urls on ImageUris?
We could instead use a ResourceUri, but I'm not 100% sure if that makes more sense.

**Comment by jonnitto** [comment]
Perhaps it is possible to get the absolute uri with `request.httpRequest`. On the other hand, it is a missing feature on the `Neos.Neos:ImageUri` prototype. We should include there the absolute flag.

**Comment by Sebobo** [comment]
Currently this seems to only be an issue with the Google Cloud Storage.
