### ISSUE TITLE
Provide fallback for og:image if none is set

### ISSUE THREAD

**Issue by Sebobo** [neos/neos-seo#97]
We take the first image that is provided in the content of the page.
This should be easily configurable via Fusion to allow integrators to verify that the output makes sense.

**Comment by DrillSergeant** [comment]
I can provide a PR for that

**Comment by Sebobo** [comment]
Thanks for the PR, I think it makes sense to not implement it as a feature now, but to use your added configurability to make it easier and to also supply documentation for that.

**Comment by Sebobo** [comment]
Resolved in #107
